// // TODO : [24/1/6] admin 테스트 완료 후 삭제
// const userId = "65981ab1a125832f20ab1315"; // admin 계정
// const userDB = "65981b71a125832f20ab1341"; // admin 채널id
// const userInfo = "6598c1a942677b4eb8c06ca0"; // db 스레드id
//
// const 프롱이 = [
//   { name: "곽연경", userId },
//   { name: "김나현", userId },
//   { name: "박종운", userId },
//   { name: "신지희", userId },
//   { name: "최용재", userId },
//   { name: "김성빈", userId },
//   { name: "김재민", userId },
//   { name: "백윤서", userId },
//   { name: "이재준", userId },
//   { name: "조재훈", userId },
//   { name: "손호민", userId },
//   { name: "안현진", userId },
//   { name: "윤석현", userId },
//   { name: "채수혁", userId },
//   { name: "허지호", userId },
//   { name: "박경빈", userId },
//   { name: "박수현", userId },
//   { name: "백준원", userId },
//   { name: "윤상민", userId },
//   { name: "하송희", userId },
//   { name: "김윤경", userId },
//   { name: "문휘식", userId },
//   { name: "이진아", userId },
//   { name: "주장권", userId },
//   { name: "김유경", userId },
//   { name: "모유경", userId },
//   { name: "최익", userId },
//   { name: "현세인", userId },
//   { name: "신준혁", userId },
//   { name: "안범", userId },
//   { name: "정혜연", userId },
//   { name: "최성민", userId },
//   { name: "최희라", userId },
//   { name: "김민수", userId },
//   { name: "배건호", userId },
//   { name: "원동건", userId },
//   { name: "이예진", userId },
//   { name: "김현주", userId },
//   { name: "이승민", userId },
//   { name: "조익준", userId },
//   { name: "지인혁", userId },
//   { name: "황재웅", userId },
//   { name: "김석주", userId },
//   { name: "신수영", userId },
//   { name: "오원주", userId },
//   { name: "황민호", userId },
//   { name: "김영현", userId },
//   { name: "안재현", userId },
//   { name: "이종혁", userId },
//   { name: "조승현", userId },
//   { name: "신종욱", userId },
//   { name: "안정은", userId },
//   { name: "이재영", userId },
//   { name: "최훈오", userId },
// ];
// const 멘토님 = [
//   { name: "소피아", userId },
//   { name: "이선협", userId },
//   { name: "로토", userId },
//   { name: "박영웅", userId },
//   { name: "노지연", userId },
//   { name: "고현주", userId },
//   { name: "김은수", userId },
//   { name: "류찬규", userId },
//   { name: "문동욱", userId },
//   { name: "박병현", userId },
//   { name: "노아", userId },
//   { name: "소인성", userId },
//   { name: "이세희", userId },
//   { name: "이희진", userId },
//   { name: "정호일", userId },
//   { name: "조윤호", userId },
//   { name: "더기", userId },
// ];
// export const USER_LIST = [...프롱이, ...멘토님];
